language: ruby

# Workaround for a Travis bug that breaks Bundler in Ruby 1.9.3.
# https://github.com/travis-ci/travis-ci/issues/5239
before_install:
  - gem install bundler

matrix:
  include:
    - os: linux
      rvm: 1.9.3
    - os: linux
      rvm: 2.0.0
    - os: linux
      rvm: 2.3.0
    - os: linux
      rvm: ruby-head
      env:
        - TEST_RUBYOPT_FROZEN_STRING_LITERAL=1
